[[constraint]]
  name = "github.com/docopt/docopt-go"
  version = "0.6.2"

[[override]]
  name = "github.com/jstemmer/go-junit-report"
  branch = "master"

[[constraint]]
  name = "github.com/karlkfi/inject"
  branch = "master"